[project]
name = "extlat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bitarray>=3.8.0",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "psutil>=7.2.1",
    "pyfim>=6.28",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
]
